# Generated by Django 3.0.2 on 2020-01-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0002_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
