# Generated by Django 3.0.2 on 2020-01-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0003_auto_20200129_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
